### ISSUE TITLE
如何往Prompt里加入图片？

### ISSUE THREAD

**Issue by Aues6uen11Z** [OpenBMB/ollama#1]
首先非常感谢你们的工作

我还是有些不清楚如何用Ollama部署使用这个模型，按照[README](https://github.com/OpenBMB/ollama/tree/minicpm-v2.5/examples/minicpm-v2.5)正常运行模型后，我模仿Ollama的[多模态模型对话写法](https://github.com/ollama/ollama?tab=readme-ov-file#multimodal-models)进行图片提问，但MiniCPMV2.5似乎没有正确接收图片。
环境：Win10，Ollama 0.1.38

![image](https://github.com/OpenBMB/ollama/assets/79563000/0ee37274-cb08-42a9-9c10-5bd7cd0c149f)

使用Open WebUI上传图片也是同样结果
![image](https://github.com/OpenBMB/ollama/assets/79563000/65c43bd7-7fce-40c2-a885-da91cc2ebf93)

Modelfile除了模型路径都没改，也没有做其他设置，可能和其他多模态模型的输入方式不太兼容？希望在这里能有更清晰的指引，非常感谢！

**Comment by Aues6uen11Z** [comment]
不好意思，我把前面构建过程给跳过了，直接用的ollama的发布包。。。
不过后面在构建的时候因为缺少[ollama/llm/patches](https://github.com/ollama/ollama/tree/main/llm/patches)报错了，同样Win10

**Comment by tc-mb** [comment]
> 首先非常感谢你们的工作
> 
> 我还是有些不清楚如何用Ollama部署使用这个模型，按照[README](https://github.com/OpenBMB/ollama/tree/minicpm-v2.5/examples/minicpm-v2.5)正常运行模型后，我模仿Ollama的[多模态模型对话写法](https://github.com/ollama/ollama?tab=readme-ov-file#multimodal-models)进行图片提问，但MiniCPMV2.5似乎没有正确接收图片。 环境：Win10，Ollama 0.1.38
> 
> ![image](https://private-user-images.githubusercontent.com/79563000/333794884-0ee37274-cb08-42a9-9c10-5bd7cd0c149f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDg0MzMsIm5iZiI6MTcxNjY0ODEzMywicGF0aCI6Ii83OTU2MzAwMC8zMzM3OTQ4ODQtMGVlMzcyNzQtY2IwOC00MmE5LTljMTAtNWJkN2NkMGMxNDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE0NDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYmNkYTFkMDg5N2MxNTM2NDlhNmI4NzViZTkwMzhmMDAxNzk2ZDQwYzNjMzFkOGU5OGNjNmJiOWE4ZTU5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.38oYmuuaeSoocrVO92PEgPC3hxrHNnj4z6MKjTYeYYs)
> 
> 使用Open WebUI上传图片也是同样结果 ![image](https://private-user-images.githubusercontent.com/79563000/333794954-65c43bd7-7fce-40c2-a885-da91cc2ebf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDg0MzMsIm5iZiI6MTcxNjY0ODEzMywicGF0aCI6Ii83OTU2MzAwMC8zMzM3OTQ5NTQtNjVjNDNiZDctN2ZjZS00MGMyLWE4ODUtZGE5MWNjMmViZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE0NDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZTc5ZDc3YjY1M2NlYTAwNzg3NGU0NWExZDczZmZkODIxNTg3MjhiYWVmYzAzNGRkNmNhMDM1ZDA5Y2U5NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G2tlx52Z0yOV-rS_3KBLk71SIJcXVA4GXRbTe9UjVTU)
> 
> Modelfile除了模型路径都没改，也没有做其他设置，可能和其他多模态模型的输入方式不太兼容？希望在这里能有更清晰的指引，非常感谢！

因为我们模型暂时不被官方支持，所以如果你的代码中ollama和llama.cpp不是我们的版本，会导致vit部分加载失败，ollama run可以运行通过，但图像特征是没有处理的，意味着模型看不到输入的图片。

为了尽快让开源社区能够使用，我们临时fork出来一份代码来支持MiniCPM-V2.5。ollama是基于llama.cpp上面做的封装，而我们也同样fork了一份llama.cpp的版本用来支持MiniCPM-V2.5。我们会尽快将我们的模型合入llama.cpp和ollama的官方。

目前使用需要支持MiniCPM-V2.5的版本的ollama和llama.cpp才可以，并且确认分支正确性。在文档最前面是说明了clone具体哪个分支。

或许以上信息可以帮到你，如果有其他问题可以继续给我讲，我会尽快回复。

**Comment by tc-mb** [comment]
> same issue here

Because our model is not officially supported now, if ollama and llama.cpp in your code are not our fork, it will cause partial loading of vit to fail, and "ollama run" can run through, but the image features are not processed, which means that the model can not see the input image.

In order to make it available to the open source community ASAP, we temporarily fork ollama to support MiniCPM-V2.5. Ollama is based on the llama.cpp, and we also have a fork of llama.cpp. We will merge our model into the official llama.cpp and ollama ASAP.

Currently, you can only use ollama and llama.cpp versions that support MiniCPM-V2.5, and confirm that the branches are correct. At the top of the document is the specific branch of the clone.

Perhaps the above information can help you, feel free to reply.

**Comment by tc-mb** [comment]
> 不好意思，我把前面构建过程给跳过了，直接用的ollama的发布包。。。 不过后面在构建的时候因为缺少[ollama/llm/patches](https://github.com/ollama/ollama/tree/main/llm/patches)报错了，同样Win10

我猜可能是你使用的分支还是主分支，或许值得确认一下是否使用的是minicpm-v2.5的子分支。

git clone -b minicpm-v2.5 https://github.com/OpenBMB/ollama.git
cd ollama/llm
git clone -b minicpm-v2.5_for_ollama https://github.com/OpenBMB/llama.cpp.git

**Comment by Aues6uen11Z** [comment]
用的确实是子分支
![image](https://github.com/OpenBMB/ollama/assets/79563000/6328f5f4-4b2f-41ba-97ad-4f90d6a65a3a)

报错是
![image](https://github.com/OpenBMB/ollama/assets/79563000/bf71c93e-d6a9-41d6-9ab3-0b5389962655)

**Comment by tc-mb** [comment]
> 用的确实是子分支 ![image](https://private-user-images.githubusercontent.com/79563000/333816359-6328f5f4-4b2f-41ba-97ad-4f90d6a65a3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjE1NDcsIm5iZiI6MTcxNjY2MTI0NywicGF0aCI6Ii83OTU2MzAwMC8zMzM4MTYzNTktNjMyOGY1ZjQtNGIyZi00MWJhLTk3YWQtNGY5MGQ2YTY1YTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE4MjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2M0MjY1MGRlZTFlM2JhNmFmN2Y0ZmJmNGY1ZjI3MmNjNDY3ZmE3ZmJjZTE3NjIyNWNlNDc5NmFhMjQ5ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Hi-u-TDx3ze5KcK0bJ_0WCyqRqTfbPscExVK664xeQ)
> 
> 报错是 ![image](https://private-user-images.githubusercontent.com/79563000/333816344-bf71c93e-d6a9-41d6-9ab3-0b5389962655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjE1NDcsIm5iZiI6MTcxNjY2MTI0NywicGF0aCI6Ii83OTU2MzAwMC8zMzM4MTYzNDQtYmY3MWM5M2UtZDZhOS00MWQ2LTlhYjMtMGI1Mzg5OTYyNjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE4MjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NzA5MzYzNDdiZDA4ZjAxYmFjYTllMTk0NWQzOGIwOGJjMjIwNDEyZmUzM2Q3NWZjZDhjZTEzMGRjMTgyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nNxYmmo5PiEuMrTOZg-juMSC-0fjlkBxtloiLNQaivo)

抱歉，我的错。
我的一些修改没有同步在window build流程里。
我已经修改了，现在应该可以正常build。
感谢。

**Comment by Aues6uen11Z** [comment]
> 抱歉，我的错。 我的一些修改没有同步在window build流程里。 我已经修改了，现在应该可以正常build。 感谢。

辛苦辛苦，之前的问题解决了，但我试了很多版本的cmake gcc构建还是有各种报错，比如

cmake 3.24.4
go 1.22.3
gcc 13.2.0 (x86_64-win32-seh-rev1, Built by MinGW-Builds project)
![image](https://github.com/OpenBMB/ollama/assets/79563000/1806c44b-62f7-42c9-9fee-e91849cfd3e3)
![image](https://github.com/OpenBMB/ollama/assets/79563000/602200af-9ef1-42fa-ae97-cbfbbf1159ff)
![image](https://github.com/OpenBMB/ollama/assets/79563000/e1890893-4b7f-43b5-8353-db854c9ff511)
[log.txt](https://github.com/OpenBMB/ollama/files/15446262/log.txt)

不清楚是哪里出了问题，要不我还是等官方合并吧=.=

**Comment by tc-mb** [comment]
> > 抱歉，我的错。 我的一些修改没有同步在window build流程里。 我已经修改了，现在应该可以正常build。 感谢。
> 
> 辛苦辛苦，之前的问题解决了，但我试了很多版本的cmake gcc构建还是有各种报错，比如
> 
> cmake 3.24.4 go 1.22.3 gcc 13.2.0 (x86_64-win32-seh-rev1, Built by MinGW-Builds project) ![image](https://private-user-images.githubusercontent.com/79563000/333850469-1806c44b-62f7-42c9-9fee-e91849cfd3e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzQxNjIsIm5iZiI6MTcxNjgzMzg2MiwicGF0aCI6Ii83OTU2MzAwMC8zMzM4NTA0NjktMTgwNmM0NGItNjJmNy00MmM5LTlmZWUtZTkxODQ5Y2ZkM2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE4MTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZTI4MjQ5OTU0NjhhYWE0OWQ4ZjcxYWU2MGIwYzkxM2FiMGNmOWU1NDAxMmUxNWZkZTBlNDQ5MGZkZGY1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lexgknkFPtTnp4REesYYVl7yWr1BbkBMHDP2eCpgRwU) ![image](https://private-user-images.githubusercontent.com/79563000/333850483-602200af-9ef1-42fa-ae97-cbfbbf1159ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzQxNjIsIm5iZiI6MTcxNjgzMzg2MiwicGF0aCI6Ii83OTU2MzAwMC8zMzM4NTA0ODMtNjAyMjAwYWYtOWVmMS00MmZhLWFlOTctY2JmYmJmMTE1OWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE4MTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZTkxYjdhZWFmZTcwZTM5NjVmMWUxNmIwZWIyOGFiMThmNGQ2MmI5YzU0NWI3MjU2OTI4NmRkMmQyNjRmOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fMdw9U9vdCNeWvHxahSEgwTtyWMCcyXIV4ncWUppvnM) ![image](https://private-user-images.githubusercontent.com/79563000/333850495-e1890893-4b7f-43b5-8353-db854c9ff511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzQxNjIsIm5iZiI6MTcxNjgzMzg2MiwicGF0aCI6Ii83OTU2MzAwMC8zMzM4NTA0OTUtZTE4OTA4OTMtNGI3Zi00M2I1LTgzNTMtZGI4NTRjOWZmNTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE4MTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2UzNzUwNmY0MzUzOTQ3NzZiOTA3MDYzOTJlZDFhMmI0NmM5NjVjNzkyNTU5ZDI0ZGIzZGRkMzkzNmI0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79zhSedltRY-BAyItTflg76Xbvh-iDFoY1mpXOUvY2U) [log.txt](https://github.com/OpenBMB/ollama/files/15446262/log.txt)
> 
> 不清楚是哪里出了问题，要不我还是等官方合并吧=.=

嗯嗯，等官方合并也是个好办法。
我们也在继续整理代码准备提PR合到官方分支。
