### ISSUE TITLE
Issue with compiling OpenBMB's ollama fork

### ISSUE THREAD

**Issue by rchen19** [OpenBMB/ollama#11]
### What is the issue?

Building on `Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-169-generic x86_64)`:

`go generate ./...` seems to work, but `go build .` gives:

```
# github.com/ollama/ollama/gpu
gpu/amd_linux.go:162:19: undefined: RocmComputeMin
gpu/amd_linux.go:232:20: undefined: IGPUMemLimit
gpu/amd_linux.go:253:19: undefined: rocmMinimumMemory
```

`nccv -V` gives:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

Attaching full terminal output for in txt file:

- `go generate ./...`
-  `go build .`

[terminaloutput.txt](https://github.com/user-attachments/files/15571681/terminaloutput.txt)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

**Comment by tc-mb** [comment]
Hi, I don't always pay attention to the issue area in this fork code repo.

1. If this issue still needs to be answered, please raise an issue in the [main repo](https://github.com/OpenBMB/MiniCPM-V) with "ollama" label. I will respond very quickly.
2. If this issue no longer needs to be answered, I will close it this week.
