### ISSUE TITLE
使用Modelfile进行打包，在run的时候报错

### ISSUE THREAD

**Issue by Dandi-China** [OpenBMB/ollama#15]
### What is the issue?

FROM ./MiniCPM-V-2_5/model/ggml-model-Q4_K_M.gguf
FROM ./MiniCPM-V-2_5/mmproj-model-f16.gguf

TEMPLATE """{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>"""

PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|eot_id|>"
PARAMETER num_keep 4
PARAMETER num_ctx 2048

使用的模型文件是CPU的gguf，原来是出现无法浏览访问外部文件系统中的文件，后来换了一下，执行run报错是Error: llama runner process has terminated: exit status 0xc0000409

### CPU

Intel

**Comment by kele527** [comment]
我也遇到了
Error: llama runner process has terminated: signal: aborted (core dumped)

**Comment by BruceJust** [comment]
这里有进展吗，我也遇到了，A100

**Comment by tc-mb** [comment]
Hi, I don't always pay attention to the issue area in this fork code repo.

1. If this issue still needs to be answered, please raise an issue in the [main repo](https://github.com/OpenBMB/MiniCPM-V) with "ollama" label. I will respond very quickly.
2. If this issue no longer needs to be answered, I will close it this week.
