### ISSUE TITLE
MAC部署2.6，'cblas.h' file not found

### ISSUE THREAD

**Issue by zhb-code** [OpenBMB/ollama#19]
### What is the issue?

在mac上部署2.6版本，执行go generate ./...时候，openblas已经安装了，就一直报错：ollama/llm/llama.cpp/ggml-blas.cpp:12:13: fatal error: 'cblas.h' file not found，怎么装都不行，该如何解决？

### OS

macOS

### GPU

Apple

### CPU

Apple

**Comment by zhb-code** [comment]
你们自己可以用mac装一下试试

**Comment by williamlee1982** [comment]
> 你们自己可以用mac装一下试试

我也碰到这个问题了，请问如何解决的？尝试了在CMakeLists.txt中指定头文件路径，但是也报了其他错误。
