### ISSUE TITLE
我下载了模型导入到ollama 但是无法识别图片

### ISSUE THREAD

**Issue by chaoqunxie** [OpenBMB/ollama#5]

**Comment by hhao** [comment]
参考  https://ollama.com/hhao/openbmb-minicpm-llama3-v-2_5

**Comment by chaoqunxie** [comment]
我使用的是ollama官方的windows安装包，加载模型的时候报错
![image](https://github.com/OpenBMB/ollama/assets/44899524/0da5a0fd-3ac8-4013-9399-7056540f5caf)

**Comment by chaoqunxie** [comment]
INFO [wmain] system info | n_threads=6 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="39764" timestamp=1716910647 total_threads=12
INFO [wmain] HTTP server listening | hostname="127.0.0.1" n_threads_http="11" port="53106" tid="39764" timestamp=1716910647
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2080 Ti, compute capability 7.5, VMM: yes
GGML_ASSERT: C:\a\ollama\ollama\llm\llama.cpp\examples\llava\clip.cpp:1026: new_clip->has_llava_projector
time=2024-05-28T23:37:28.074+08:00 level=ERROR source=sched.go:344 msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000409 " 这是server.log

**Comment by chaoqunxie** [comment]
> 参考 https://ollama.com/hhao/openbmb-minicpm-llama3-v-2_5

官方ollama 使用你的模型也会报错 
![image](https://github.com/OpenBMB/ollama/assets/44899524/09ebc905-89f5-4555-90ba-69b370d9a7ca)

**Comment by rhchenxm** [comment]
ollama当前的版本还不支持，需要下载OpenBMB修改后源码进行编译的版本才能支持。
编译方法如下：
https://github.com/OpenBMB/ollama/tree/minicpm-v2.5/examples/minicpm-v2.5

**Comment by hhao** [comment]
> > 参考 https://ollama.com/hhao/openbmb-minicpm-llama3-v-2_5
> 
> 能否提供F16的tag

已上传

**Comment by svcvit** [comment]
> > > 参考 https://ollama.com/hhao/openbmb-minicpm-llama3-v-2_5
> > 
> > 
> > 能否提供F16的tag
> 
> 已上传

能否提供遍历的 ollama，我按照你的步骤编译完，还是无法识别图片。感谢

**Comment by chaoqunxie** [comment]
> > > > 参考 https://ollama.com/hhao/openbmb-minicpm-llama3-v-2_5
> > > 
> > > 
> > > 能否提供F16的tag
> > 
> > 
> > 已上传
> 
> 能否提供遍历的 ollama，我按照你的步骤编译完，还是无法识别图片。感谢

能否编译成windows10 64位的安装包，还是希望推动官方尽快支持面壁者小钢炮

**Comment by chaoqunxie** [comment]
> mac的m芯片编译了一个ollama，可以正常使用了
> 
> <img alt="image" width="962" src="https://private-user-images.githubusercontent.com/3839507/334779446-e6b7339a-c9df-4ae8-8782-568e3e5edad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDI4NDMsIm5iZiI6MTcxNzA0MjU0MywicGF0aCI6Ii8zODM5NTA3LzMzNDc3OTQ0Ni1lNmI3MzM5YS1jOWRmLTRhZTgtODc4Mi01NjhlM2U1ZWRhZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDQxNTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ4NGVmMmQyMTEyY2Q2ZmFiNWMxZmUzYWQxOWE4YTg4OWNjNGRlOWEyOTI1ZTM1OGE5MDIyYTNkNDJmODMxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pje-Huo0L1X3X7_1Yzg7Pg4g7PgS_xxI-WJLZRIgDTw">
> https://www.alipan.com/s/8gxrfmmw75X

效果怎么样
^_^

**Comment by tc-mb** [comment]
Hi, I don't always pay attention to the issue area in this fork code repo.

1. If this issue still needs to be answered, please raise an issue in the [main repo](https://github.com/OpenBMB/MiniCPM-V) with "ollama" label. I will respond very quickly.
2. If this issue no longer needs to be answered, I will close it this week.
