### ISSUE TITLE
放出一个release版本试用？

### ISSUE THREAD

**Issue by yuezhishun** [OpenBMB/ollama#8]
试用成本有点高，能不能给一个安装包试用一下

**Comment by tc-mb** [comment]
> 试用成本有点高，能不能给一个安装包试用一下

目前分支还没有合并，这可能不太容易。
或许可以等我们的分支合并进官方再说。

**Comment by hhao** [comment]
https://github.com/hhao/ollama/releases

**Comment by yuezhishun** [comment]
非常感谢，能否提供一个windows下可用的安装包

**Comment by tc-mb** [comment]
Hi, I don't always pay attention to the issue area in this fork code repo.

1. If this issue still needs to be answered, please raise an issue in the [main repo](https://github.com/OpenBMB/MiniCPM-V) with "ollama" label. I will respond very quickly.
2. If this issue no longer needs to be answered, I will close it this week.
