### ISSUE TITLE
CPM support function calling ability?

### ISSUE THREAD

**Issue by yhyu13** [OpenBMB/ollama#9]
Hi,

Would you like to create a model with Visual function calling abilities (like corping images, indexing items, so on and so forth) beyond visual QA?

Thanks!

**Comment by tc-mb** [comment]
> Hi,
> 
> Would you like to create a model with Visual function calling abilities (like corping images, indexing items, so on and so forth) beyond visual QA?
> 
> Thanks!

Thank you for your question, we are very concerned about this kind of capabilities, and believe that this is also the direction of the development of multimodal models, but I am not sure when these features will really work.
